# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters: null

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    Bits\Themply\:
    # resource: '../src/'
    # exclude:
    #     - '../src/DependencyInjection/'
    #    - '../src/Entity/'
    #    - '../src/Kernel.php'
    
    

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Bits\Themply\Controller\Sort:
        arguments:
             - '@contao.routing.scope_matcher'
             - '@Bits\Themply\Service\TableNameExtractor'
             - '@Bits\Themply\Service\Sorter'
        tags:
             - 'controller.service_arguments'

    Bits\Themply\EventListener\LoadDataContainerListener:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@request_stack'
            - '@contao.framework'
            - '@contao.csrf.token_manager'
            - '@twig'
            - '@router'
            - '@Bits\Themply\Service\Sorter'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    Bits\Themply\Service\TableNameExtractor: null

    Bits\Themply\Service\Sorter:
        arguments:
            - '@database_connection'
    Bits\Themply\:
        resource: ../src
        exclude: 
            - ../src/{ContaoManager,DependencyInjection}
         #   - '../src/Contao/ThemplyModule.php'
         #   - '../src/Eventlistener/'